"""Every wording the Origin fold can show, rendered by the page's own code.

    python -m forecast.originwording            # rewrite the permutations
    python -m forecast.originwording --check    # exit 1 if they are out of date

`docs/origin_wording.md` states the owner's formula (2026-10-10): each of an
origin's three lines is a fixed run of slots, and a slot with no value is
dropped with its joining words. Its last section shows every permutation, and
this writes it: the Origin functions are lifted out of `app/forecast.html`
and run in Node on one made-up Origin block per branch, so the examples are
what the page prints, never typed. `tests/test_originwording.py` pins that
the file is this output, so the doc and the page cannot drift.

The numbers in the cases are made up; only the wording is under review.
Dates are Pacific, the reader's zone at these beaches.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / "app" / "forecast.html"
DOC = ROOT / "docs" / "origin_wording.md"
#: Everything below this line in the doc is generated.
MARKER = "<!-- Generated by python -m forecast.originwording. Edit above this line. -->"

NAMES = {"46232": "Point Loma South, CA", "46047": "Tanner Banks, CA",
         "46086": "San Clemente Basin, CA"}
BASE = {"station": "46232", "bearing_stations": ["46047"], "lookback_days": 21,
        "station_names": NAMES}


def _arrival(**over) -> dict:
    a = {"first_utc": "2026-10-07T06:00:00Z", "last_utc": "2026-10-09T18:00:00Z",
         "hours_read": 18.4, "lead_period_s": 18.2, "latest_period_s": 14.1,
         "peak_period_s": 15.4, "distance_km": 7400, "generated_utc": "2026-10-01T12:00:00Z",
         "bearing_deg": None, "bearing_from": None, "bearing_lobes": [], "origin": None,
         "region": None}
    a.update(over)
    return a


PLACED = {"bearing_deg": 212, "bearing_from": "46047", "origin": [-40.0, -150.0],
          "region": "the South Pacific"}
SPLIT = {"bearing_from": "46047", "bearing_lobes": [[205, 0.55], [285, 0.31]]}
UNSEEN: dict = {}


def _hurricane(**over) -> dict:
    h = {"storm": "EP182026", "name": "Rachel", "peak_kt": 105, "best": 0.92, "word": "strong",
         "match": {"46047": {"score": 0.92, "beaten": 46, "trials": 50, "hours": 30}},
         "sites": {"buoy": {"train_period_s": 14.3, "fix_utc": "2026-10-02T00:00:00Z",
                            "lat": 19.4, "lon": -109.6, "distance_km": 1680,
                            "bearing_deg": 196, "vmax_kt": 105, "mslp_mb": 950}}}
    h.update(over)
    return h


def _no_pressure() -> dict:
    h = _hurricane()
    h["sites"]["buoy"]["mslp_mb"] = None
    return h


def _site(current=(), last=None) -> dict:
    return {"buoy": {"current": [{"arrival": k, "train_period_s": p} for k, p in current],
                     "last": last}}


#: (id, what it is, the Origin block). One per branch the page can take.
CASES = [
    ("E0", "nothing in 21 days", {"arrivals": [], "sites": _site()}),
    ("L1", "last readable arrival, placed",
     {"arrivals": [_arrival(**PLACED)], "sites": _site(last=0)}),
    ("L2", "last readable arrival, split direction",
     {"arrivals": [_arrival(**SPLIT)], "sites": _site(last=0)}),
    ("L3", "last readable arrival, unplaced (46047 does not have it)",
     {"arrivals": [_arrival(**UNSEEN)], "sites": _site(last=0)}),
    ("C1", "arriving, placed",
     {"arrivals": [_arrival(**PLACED)], "sites": _site(current=[(0, 15.1)])}),
    ("C2", "arriving, split direction",
     {"arrivals": [_arrival(**SPLIT)], "sites": _site(current=[(0, 15.1)])}),
    ("C3", "arriving, unplaced",
     {"arrivals": [_arrival(**UNSEEN)], "sites": _site(current=[(0, 15.1)])}),
    ("C4", "arriving, one of each",
     {"arrivals": [_arrival(**PLACED),
                   _arrival(**SPLIT, distance_km=5200, generated_utc="2026-10-03T00:00:00Z"),
                   _arrival(distance_km=3100, generated_utc="2026-10-05T00:00:00Z")],
      "sites": _site(current=[(0, 15.1), (1, 13.2), (2, 11.8)])}),
    ("H1", "hurricane, one gate buoy",
     {"arrivals": [], "sites": _site(), "hurricanes": [_hurricane()]}),
    ("H2", "hurricane, two gate buoys",
     {"arrivals": [], "sites": _site(), "hurricanes": [_hurricane(
         best=0.78, word="partial",
         match={"46086": {"score": 0.70, "beaten": 28, "trials": 40, "hours": 26},
                "46047": {"score": 0.78, "beaten": 39, "trials": 50, "hours": 30}})]}),
    ("H3", "hurricane, weak, no hours, no pressure",
     {"arrivals": [], "sites": _site(), "hurricanes": [dict(_no_pressure(),
         best=0.55, word="weak",
         match={"46047": {"score": 0.55, "beaten": 11, "trials": 20, "hours": None}})]}),
    ("M1", "hurricane and a placed reading",
     {"arrivals": [_arrival(**PLACED)], "sites": _site(current=[(0, 15.1)]),
      "hurricanes": [_hurricane()]}),
    ("M2", "hurricane and a last readable arrival (the last is not shown)",
     {"arrivals": [_arrival(**PLACED)], "sites": _site(last=0),
      "hurricanes": [_hurricane()]}),
]


def _lift(source: str, start: str, end: str) -> str:
    a = source.index(start)
    return source[a:source.index(end, a) + len(end)]


def script(source: str) -> str:
    """The page's Origin code and its helpers, and a loop printing each case."""

    code = "\n".join([
        "let NOW = null;",
        _lift(source, "const MPH_PER_KT = ", ";"),
        _lift(source, "const MI_PER_KM = ", ";"),
        _lift(source, "const speed = ", "</span>`);"),
        _lift(source, "function point(", "\n}\n"),
        _lift(source, "const period = ", ");"),
        _lift(source, "function srcLines(", "\n}\n"),
        source[source.index("function originFor("):source.index("// Whether Origin is folded out")],
    ])
    cases = json.dumps([[cid, {**BASE, "hurricanes": [], **block}] for cid, _, block in CASES])
    return code + f"""
const text = (html) => html
  .replace(/<span class="(turn|src)">/g, "\\n").replace(/<div class="origin"[^>]*>/g, "\\n")
  .replace(/ <span class="unit">(?!\\()/g, "  ")
  .replace(/<[^>]+>/g, "").replace(/&nbsp;/g, " ").replace(/&deg;/g, "°")
  .split("\\n").map((s) => s.trim()).filter(Boolean);
const out = {{}};
for (const [id, origin] of {cases}) {{
  NOW = {{origin}};
  out[id] = text(originBody(originFor("buoy")));
}}
console.log(JSON.stringify(out));
"""


def render(source: str | None = None) -> dict[str, list[str]]:
    node = shutil.which("node")
    if node is None:
        raise RuntimeError("node is not installed")
    source = PAGE.read_text(encoding="utf-8") if source is None else source
    env = dict(os.environ, TZ="America/Los_Angeles", LANG="en_US.UTF-8", LC_ALL="en_US.UTF-8")
    got = subprocess.run([node, "-e", script(source)], capture_output=True, text=True,
                         env=env, check=True)
    return json.loads(got.stdout)


def permutations(rendered: dict[str, list[str]]) -> str:
    parts = [MARKER, ""]
    for cid, title, _ in CASES:
        parts += [f"### {cid}: {title}", "", "```text", *rendered[cid], "```", ""]
    return "\n".join(parts)


def build(doc: str, rendered: dict[str, list[str]]) -> str:
    head = doc[:doc.index(MARKER)] if MARKER in doc else doc.rstrip("\n") + "\n\n"
    return head + permutations(rendered)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the doc is out of date")
    args = parser.parse_args(argv)
    doc = DOC.read_text(encoding="utf-8")
    want = build(doc, render())
    if args.check:
        if want != doc:
            print(f"{DOC.relative_to(ROOT)} is out of date: run python -m forecast.originwording")
            return 1
        return 0
    DOC.write_text(want, encoding="utf-8")
    print(f"wrote {DOC.relative_to(ROOT)}: {len(CASES)} cases")
    return 0


if __name__ == "__main__":
    sys.exit(main())
